services:
  dev:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/app
      - uv-cache:/home/appuser/.cache/uv
    working_dir: /app
    command: tail -f /dev/null
    user: appuser
    
  prod:
    build:
      context: .
      dockerfile: Dockerfile.production
    env_file:
      - .env
    volumes:
      - ./auth:/app/auth:ro
      - ./settings:/app/settings:ro
    working_dir: /app
    command: python -m autojournalsummarizer.main
    user: appuser
    restart: unless-stopped
    
volumes:
  uv-cache:
