version: '3'
services:
  journalgpt:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        UID: 1000
        GID: 1000
        USERNAME: app
        GROUPNAME: app
    logging:
      driver: syslog
    env_file:
      - .env
    volumes:
      - ./code:/home/app/code
    working_dir: /home/app/code
    command: tail -f > /dev/null
