services:
  dev:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
      args:
        UID: 1000
        GID: 1000
        USERNAME: app
        GROUPNAME: app
    env_file:
      - .env
    volumes:
      - ./:/home/app/project
      - python-packages:/home/app/.local/share
    working_dir: /home/app/project
    command: tail -f > /dev/null
  prod:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        UID: 1000
        GID: 1000
        USERNAME: app
        GROUPNAME: app
    env_file:
      - .env
    volumes:
      - ./auth:/home/app/project/auth
      - ./settings:/home/app/project/settings
    working_dir: /home/app/project
    command: python main.py
volumes:
  python-packages:
