FROM python:3.10

RUN apt-get update \
    && apt-get -y install locales libsndfile1 \
    && localedef -f UTF-8 -i ja_JP ja_JP.UTF-8
ENV LANG=ja_JP.UTF-8 LANGUAGE=ja_JP:ja LC_ALL=ja_JP.UTF-8 TZ=JST-9

# Entrykitのインストール
ENV ENTRYKIT_VERSION 0.4.0
RUN wget https://github.com/progrium/entrykit/releases/download/v${ENTRYKIT_VERSION}/entrykit_${ENTRYKIT_VERSION}_Linux_x86_64.tgz \
    && tar -xvzf entrykit_${ENTRYKIT_VERSION}_Linux_x86_64.tgz \
    && rm entrykit_${ENTRYKIT_VERSION}_Linux_x86_64.tgz \
    && mv entrykit /bin/entrykit \
    && chmod +x /bin/entrykit \
    && entrykit --symlink

# ユーザー追加
ARG UID=1000
ARG GID=1000
ARG USERNAME=app
ARG GROUPNAME=app
RUN groupadd -g ${GID} ${GROUPNAME} && \
    useradd -m -s /bin/bash -u ${UID} -g ${GID} ${USERNAME}
USER ${USERNAME}

# pipenvインストール
RUN pip install --upgrade pip && pip install pipenv
ENV PATH ${PATH}:/home/${USERNAME}/.local/bin
ENV PIPENV_VERBOSITY -1
RUN mkdir /home/${USERNAME}/.local/share

# ログイン時に仮想環境が立ち上がっていなければ立ち上げる
RUN echo "if [[ -z \"\${VIRTUAL_ENV}\" ]]; then" >> /home/${USERNAME}/.bashrc && \
    echo "source \$(pipenv --venv)/bin/activate" >> /home/${USERNAME}/.bashrc && \
    echo "fi"                                    >> /home/${USERNAME}/.bashrc

# Entrypointの設定
COPY entrypoints/ /opt/bin/
ENTRYPOINT [ \
    "prehook", "/opt/bin/docker-setup.sh", "--", \
    "/opt/bin/docker-entrypoint.sh"]
