services:
  dev:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      target: development
    env_file:
      - .env
    volumes:
      - ./:/workspace
      - uv-cache:/home/vscode/.cache/uv
      - claude-data:/home/vscode/.claude
      - gemini-data:/home/vscode/.gemini
    working_dir: /workspace
    command: tail -f /dev/null
    user: vscode

  prod:
    build:
      context: .
      dockerfile: Dockerfile.production
    env_file:
      - .env
    volumes:
      - ./auth:/app/auth:ro
      - ./settings:/app/settings:ro
    working_dir: /app
    command: python -m autojournalsummarizer.main
    user: appuser
    restart: unless-stopped

volumes:
  uv-cache:
  claude-data:
  gemini-data:
